#!/usr/bin/env python3
import re
import subprocess


def main():
    kwargs = {
        'stdout': subprocess.PIPE,
        'encoding': 'utf-8',
    }
    modified = re.compile('^\s?[AM]+\s+(?P<name>.*\.py)', re.MULTILINE)
    files = subprocess.run(['git', 'status', '--porcelain'], **kwargs).stdout
    files = modified.findall(files)

    if not files:
        return

    output = subprocess.run(['flake8', ] + files, **kwargs).stdout

    if output:
        print(
            'PEP8/Lint/Complexity style violations have been detected.',
            'Please fix them or force the commit with "git commit --no-verify".\n',
            output,
            sep='\n',
            end='',
        )
        raise SystemExit(1)


if __name__ == '__main__':
    main()
