
silent! py3 pass
scriptencoding utf-8
set encoding=utf-8
set number
set nocompatible              " be iMproved, required
filetype off                  " required


if has("syntax")
    syntax on
endif

" Plug
source $HOME/.vim/vimrc/plug.vim

" COC
source $HOME/.vim/vimrc/coc.vim

" My config
source $HOME/.vim/vimrc/my_config.vim
